services:
  - type: web
    name: event-app-server
    env: node
    buildCommand: yarn install && yarn build && prisma migrate deploy
    startCommand: yarn start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        value: production
